version: '3.8'

services:
  frontend:
    build: ./research_assistant_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./research_assistant_frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

  backend:
    build: ./ugadhi_special_cal
    ports:
      - "8000:8000"
    volumes:
      - ./ugadhi_special_cal:/app